### PR TITLE
Task 3224950: Fix issue causing Office-Addin-Taskpane-Js project to fail

### PR DESCRIPTION
**Pull request by TCourtneyOwen**
- After adding the babel-polyfill I no longer hit this issue.  I originally tried this fix out because I saw that we are doing this in the current generator-office jquery javascript template

### CODE REVIEW

**Comment by akrantz** [comment]
@TCourtneyOwen I think we should make this commit first to Office-Addin-TaskPane, then merge through to Office-Addin-TaskPane-JS, and others.

**Comment by akrantz** [comment]
@TCourtneyOwen Did this change need to go into Office-Addin-TaskPane?

**Comment by akrantz** [comment]
or maybe it's already in there and this just should be closed...

**Comment by TCourtneyOwen** [comment]
Fix is already in and was checked as part of previous merge. Closing PR

**Pull request closed without merging**
