### PR TITLE
Merge changes from Office-Addin-TaskPane

### PR DESCRIPTION
**Pull request by akrantz**

### CODE REVIEW

**Comment by TCourtneyOwen** [comment]
Hmm need to see why this build failed - may be a problem with the configuration of the build task in the pipeline

**Comment by TCourtneyOwen** [comment]
Yup error with build task. I think I just fixed it. Will kick off this job again

**Comment by akrantz** [comment]
##[error]Error: ENOENT: no such file or directory, stat 'C:\AzureAgent\_work\3\s\run build'

**Comment by TCourtneyOwen** [comment]
Fixed

**Comment by akrantz** [comment]
What did you do? Are you kicking off another build?

**Comment by TCourtneyOwen** [comment]
I sent you results from manually queue after updating build tasks. Dumb configuration error

**Comment by akrantz** [comment]
See https://github.com/OfficeDev/Office-Addin-TaskPane-JS/pull/13.

**Pull request closed without merging**
