### PR TITLE
Draft PR: default-js template for WXP on Toolkit

### PR DESCRIPTION
**Pull request by YueLi-MSFT**
Thank you for your pull request!  Please provide the following information.

---

**Change Description**:

    Describe what the PR is about. 

1. **Do these changes impact any *npm scripts* commands (in package.json)?** (e.g., running 'npm run start')
    If Yes, briefly describe what is impacted.

2. **Do these changes impact *VS Code debugging* options (launch.json)?**
    If Yes, briefly describe what is impacted.

3. **Do these changes impact *template output*?** (e.g., add/remove file, update file location, update file contents)
    If Yes, briefly describe what is impacted.

4. **Do these changes impact *documentation*?** (e.g., a tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
    If Yes, briefly describe what is impacted.

If you answered yes to any of these please do the following:
    > Include 'Rick-Kirkham' in the review
    > Make sure the README file is correct

**Validation/testing performed**:

    Describe manual testing done.

### CODE REVIEW

**Review by millerds — CHANGES_REQUESTED** [review]
This repo needs to continue to support all host for xml and not be converted to just json for your specific scenario.  There are changes being made to the repo to support both json and xml and you should wait and base your changes of that.

I would also note that when generating projects we currently have the user pick hosts to start with.  If you want to change from that either to add the option for all hosts or to replace host specific options with always generating for all hosts then some more thought need to go into the design of the template with others (documentation team owns the content of the project and Outlook team should have a say) such that it's not overly complicated and easy enough to trim down when developers don't want everything.

**Comment by YueLi-MSFT** [comment]
> This repo needs to continue to support all host for xml and not be converted to just json for your specific scenario. There are changes being made to the repo to support both json and xml and you should wait and base your changes of that.
> 
> I would also note that when generating projects we currently have the user pick hosts to start with. If you want to change from that either to add the option for all hosts or to replace host specific options with always generating for all hosts then some more thought need to go into the design of the template with others (documentation team owns the content of the project and Outlook team should have a say) such that it's not overly complicated and easy enough to trim down when developers don't want everything.



> This repo needs to continue to support all host for xml and not be converted to just json for your specific scenario. There are changes being made to the repo to support both json and xml and you should wait and base your changes of that.
> 
> I would also note that when generating projects we currently have the user pick hosts to start with. If you want to change from that either to add the option for all hosts or to replace host specific options with always generating for all hosts then some more thought need to go into the design of the template with others (documentation team owns the content of the project and Outlook team should have a say) such that it's not overly complicated and easy enough to trim down when developers don't want everything.

Hi Darren, our specific scenario is only for MetaOS feature (Teams Toolkit) and only support Json manifest, could you please help to create a new branch for us to merge because we have access to create new branch? Or do you have any better suggestions? Additionally, I believe that it would be beneficial for us to have further discussions with the documentation team and the Outlook team regarding the generation of projects for all hosts, as you mentioned. Thanks Darren! :)

**Comment by YueLi-MSFT** [comment]
> This repo needs to continue to support all host for xml and not be converted to just json for your specific scenario. There are changes being made to the repo to support both json and xml and you should wait and base your changes of that.
> 
> I would also note that when generating projects we currently have the user pick hosts to start with. If you want to change from that either to add the option for all hosts or to replace host specific options with always generating for all hosts then some more thought need to go into the design of the template with others (documentation team owns the content of the project and Outlook team should have a say) such that it's not overly complicated and easy enough to trim down when developers don't want everything.

Hi Darren, our specific scenario is only for MetaOS feature (Teams Toolkit) and only support Json manifest, could you please help to create a new branch for us to merge because we have access to create new branch? Or do you have any better suggestions? Additionally, I believe that it would be beneficial for us to have further discussions with the documentation team and the Outlook team regarding the generation of projects for all hosts, as you mentioned. Thanks Darren! :)

**Comment by millerds** [comment]
I understand your scenario is just for json manifests, but we want to keep the number of branches and repos under control so we don't get to much to maintain.  Since most of the template is the same across different scenarios we make it so the repo houses things for all of them and then use the conversion script to reduce the result down to a specific case.  I if you look at https://github.com/OfficeDev/Office-Addin-TaskPane-JS/pull/130 you'll see what we're doing to support xml and json in the same repo and branch.  The generator-office code will be updated to make the right script call.  Similar changes will need to be made to the toolkit code and eventually the conversion script will need to be updated to support WXP.

**Comment by YueLi-MSFT** [comment]
> I understand your scenario is just for json manifests, but we want to keep the number of branches and repos under control so we don't get to much to maintain. Since most of the template is the same across different scenarios we make it so the repo houses things for all of them and then use the conversion script to reduce the result down to a specific case. I if you look at #130 you'll see what we're doing to support xml and json in the same repo and branch. The generator-office code will be updated to make the right script call. Similar changes will need to be made to the toolkit code and eventually the conversion script will need to be updated to support WXP.

Thanks Darren! You make a good point, and I couldn't agree with you more. I will resend PRs based on #130. 
I have 2questions here:
1. How long do these take for #130 and [https://github.com/OfficeDev/Office-Addin-TaskPane/pull/225](url) to check in to the master branch? 
2. By the way, will you support xml and json manifest in these repos (Office-Addin-Taskpane-React and Office-Addin-Taskpane-React-JS)? 
Thanks for your reply!

**Comment by millerds** [comment]
> > I understand your scenario is just for json manifests, but we want to keep the number of branches and repos under control so we don't get to much to maintain. Since most of the template is the same across different scenarios we make it so the repo houses things for all of them and then use the conversion script to reduce the result down to a specific case. I if you look at #130 you'll see what we're doing to support xml and json in the same repo and branch. The generator-office code will be updated to make the right script call. Similar changes will need to be made to the toolkit code and eventually the conversion script will need to be updated to support WXP.
> 
> Thanks Darren! You make a good point, and I couldn't agree with you more. I will resend PRs based on #130. I have 2questions here:
> 
> 1. How long do these take for [Add support for the unified manifest #130](https://github.com/OfficeDev/Office-Addin-TaskPane-JS/pull/130) and [https://github.com/OfficeDev/Office-Addin-TaskPane/pull/225](url) to check in to the master branch?
> 2. By the way, will you support xml and json manifest in these repos (Office-Addin-Taskpane-React and Office-Addin-Taskpane-React-JS)?
>    Thanks for your reply!

Hopefully the PR will be checked in this week (just one more issue to work out)

I image the same thing will be done for other repos . . . but that is something we have to work out with Ricky.

**Pull request closed without merging**
