### PR TITLE
npm audit fix addresses all vulnerabilities

### PR DESCRIPTION
**Pull request by TCourtneyOwen**

### CODE REVIEW

**Comment by akrantz** [comment]
@TCourtneyOwen  There is a merge conflict for package-lock.json. Did you really start from a clean master branch to create the fix-vulnerabilities branch, or are you reusing a branch?  I can sometimes reuse the branch name but I delete the branch then create a new branch off of master with that name.

**Comment by TCourtneyOwen** [comment]
I believe I did. Maybe I made a mistake with this particular repo

**Comment by TCourtneyOwen** [comment]
Let me start over for this repo

**Comment by TCourtneyOwen** [comment]
You are right, I didn't start from a clean branch.  After trying this again, I didn't find any vulnerabilities on this repo, so need for any changes

**Pull request closed without merging**
